import type {
  CheckpointRequest as GeneratedCheckpointRequest,
  DiskRevision as GeneratedDiskRevision,
  DocumentSnapshot as GeneratedDocumentSnapshot,
  ExportOutcome as GeneratedExportOutcome,
  ExportRequest as GeneratedExportRequest,
  ExternalChange as GeneratedExternalChange,
  RecoveryEntry as GeneratedRecoveryEntry,
  RecoverySnapshot as GeneratedRecoverySnapshot,
  SaveDocumentRequest as GeneratedSaveDocumentRequest,
  SaveOutcome as GeneratedSaveOutcome,
  SearchHit as GeneratedSearchHit,
  SearchRequest as GeneratedSearchRequest,
  SettingsV1 as GeneratedSettingsV1,
  SessionTabV1 as GeneratedSessionTabV1,
  SessionV1 as GeneratedSessionV1,
  WorkspaceEntry as GeneratedWorkspaceEntry,
  WorkspaceSnapshot as GeneratedWorkspaceSnapshot,
  WriteAssetRequest as GeneratedWriteAssetRequest,
  WriteAssetResult as GeneratedWriteAssetResult,
} from "./generated";
import type { Text } from "@codemirror/state";

// IPC shapes originate in Rust and are generated by `pnpm bindings`.
// The few aliases below narrow validated string values for safer UI code.
export type CheckpointRequest = GeneratedCheckpointRequest;
export type DiskRevision = GeneratedDiskRevision;
export type DocumentSnapshot = GeneratedDocumentSnapshot;
export type SaveDocumentRequest = GeneratedSaveDocumentRequest;
export type SaveOutcome = GeneratedSaveOutcome;
export type SearchHit = GeneratedSearchHit;
export type SearchRequest = GeneratedSearchRequest;
export type WorkspaceEntry = GeneratedWorkspaceEntry;
export type WorkspaceSnapshot = GeneratedWorkspaceSnapshot;
export type WriteAssetRequest = GeneratedWriteAssetRequest;
export type WriteAssetResult = GeneratedWriteAssetResult;
export type RecoverySnapshot = GeneratedRecoverySnapshot;

export type ExternalChange = Omit<GeneratedExternalChange, "kind"> & {
  kind: "modified" | "deleted";
};

export type ExportRequest = Omit<GeneratedExportRequest, "pageSize"> & {
  pageSize: "A4" | "Letter" | null;
};

export type ExportOutcome = Omit<GeneratedExportOutcome, "action"> & {
  action: "saved" | "print";
};

export type RecoveryEntry = Omit<GeneratedRecoveryEntry, "kind"> & {
  kind: "draft" | "history" | string;
};

export type SettingsV1 = Omit<GeneratedSettingsV1, "locale" | "theme"> & {
  locale: "system" | "zh-CN" | "en-US";
  theme: "system" | "light" | "dark";
};

export type SessionTabV1 = Omit<GeneratedSessionTabV1, "mode"> & {
  mode: "live" | "source" | "preview";
};

export type SessionV1 = Omit<GeneratedSessionV1, "tabs"> & {
  tabs: SessionTabV1[];
};

export interface ApiError {
  code: string;
  message: string;
}

export interface DocumentTab extends Omit<DocumentSnapshot, "content"> {
  content: Text;
  editorVersion: number;
  dirty: boolean;
  saveState: "saved" | "saving" | "dirty" | "error";
  mode: "live" | "source" | "preview";
  externalChange: ExternalChange | null;
  allowRemoteImages: boolean;
}
